FROM almalinux:9
RUN dnf install nginx -y

CMD ["nginx", "-g", "daemon off;"]

LABEL author="ganesh"\
      company="Infosys"\
      topic="Devops"
ENV trainer="SHiVA"

LABEL The trainer is="$trainer"
